### PR TITLE
updates

### PR DESCRIPTION
**Pull request by mambax7**

### CODE REVIEW

**Comment by mambax7** [comment]
Let me test and fix it. Sorry for this :(

**Comment by mambax7** [comment]
Adding groups and videos works here. You might need to update your DB.

**Comment by mambax7** [comment]
Audio upload didn't work 👎 
I'll look into it

**Comment by liomj** [comment]
> Adding groups and videos works here. You might need to update your DB.

i made  a new install. im having the same issue. i'll try again  

templates also need to be rename

**Comment by mambax7** [comment]
It uploaded the audio file, just didn't insert the info into DB. 
I'm still looking...

**Comment by liomj** [comment]
i've deleted the yogurt folder and remove the yogurt database and install your latest changes and 

Im still having issues with groups, audios,videos etc 

when using sample data audios, groups,videos,photos is missing
can't upload audios, post videos
can't create groups
etc

**Comment by mambax7** [comment]
That's not good :(  
Are you using a local server, or a an external host? 

Let me finish creating the test data, and then I'll reinstall here to test it.

**Comment by liomj** [comment]
Im using local wamp server

**Comment by mambax7** [comment]
OK, I'm using it as well.  Give me an hour or so to work on the Test Data, and then I'll reinstall it here and test it.

**Comment by mambax7** [comment]
What PHP do you use? I'm using the latest 7.4.5

**Comment by liomj** [comment]
> OK, I'm using it as well.  Give me an hour or so to work on the Test Data, and then I'll reinstall it here and test it. 

Ok thank you Mamba take your time

Im using php 7.3.12, mysql 5.728, xoops 2.5.11 beta

By the way i noticed you changed some db name such as yogurt_groups to yogurtgroups in class/groups.php

 is that on purpose or accidental

**Comment by mambax7** [comment]
Oops! That was accidental. 
It will be all fixed! :)

**Comment by mambax7** [comment]
Which line was it? 
I've changed to use Constants, e.g.:
```php
$sql   = 'SELECT * FROM ' . $this->xoopsDb->prefix(YOGURTGROUPS) . ' WHERE group_id=' . $id;
```

but the constant was defined here:

```php
  const YOGURTGROUPS = 'yogurt_groups'; //table
```

**Comment by liomj** [comment]
So i see that was on purpose

**Comment by mambax7** [comment]
Yes, this was on purpose. SonarLint was complaining too much, so I wanted to try with the Constants :) 

I'm letting the code run through the SonarLint:
https://sonarcloud.io/dashboard?id=mambax7_yogurt2
and Scrutinizer:
https://scrutinizer-ci.com/g/mambax7/yogurt/

to get some help :)

**Comment by liomj** [comment]
I learned something new everyday...nice tools

**Comment by mambax7** [comment]
There are links to them in the Readme file: https://github.com/XoopsModules25x/yogurt/
image

**Comment by liomj** [comment]
1. error inserting new videos
0.000185 - INSERT INTO yogurt_videos (video_id, uid_owner, video_desc, youtube_code, main_video)VALUES (0, 1, 'y', '29EMrDrjCIo', '')
Error number: 1366
Error message: Incorrect integer value: '' for column 'main_video' at row 1

2. mainvideos.php missing

**Comment by liomj** [comment]
1. after updating pictures - images is missing
2. cant upload audios
3. friend is missing in sample data

4. can't create new group

Errors
--
Notice: Undefined offset: 0 in file /modules/yogurt/group.php line 39
Error: Error: Call to a member function getVar() on null in file /modules/yogurt/group.php line 76

**Comment by mambax7** [comment]
- Can you try a new installation and import the the Sample Test Data? 
- Uploading the audio and the group creation are still on my TODO list
- Friend data is in the Sample Data: https://github.com/mambax7/yogurt/blob/master/testdata/english/yogurt_friendships.yml

**Comment by liomj** [comment]
> * Can you try a new installation and import the Sample Data?
> * Uploading the audio and the group creation are still on my TODO list
> * Friend data is in the Sample Data: https://github.com/mambax7/yogurt/blob/master/testdata/english/yogurt_friendships.yml

in the tab its showing 2 friends but in the index page and friends page no friends are listed

**Comment by mambax7** [comment]
You need to add one extra user with the Id: 999 
I'll need to add it to the Installation

**Comment by liomj** [comment]
why we just dont use id 2 or 3 for sampe data

**Comment by mambax7** [comment]
Because if people want to test the module on an existing installation, this could cause a problem if they have already users with the ID as 2 and 3 
So that's why I used the high numbers, but we could go even higher, like 9999 :) 
image

**Comment by liomj** [comment]
may i know what problem might arise ? i dont think it would create problem since its just for testing purpose..user can just unfriend

if we add new user eg id 999 in the installation, we need to check the user exist first and delete the user again before reinstall

**Comment by mambax7** [comment]
You don't want to touch existing users in any way, because if something goes wrong, you might lose the data, and they users might not be very happy.  While the testing should be done on a test site, some people will test it on a production site, and we don't want to be responsible for any disasaster 
So my recommendation was to install with a very high number, like 9999 or 99999

**Comment by liomj** [comment]
alright noted mamba

one anther minor issue group number 10 group image is missing for sample data

**Comment by mambax7** [comment]
BTW - if it easier for you, we could have two sets of test data, one with 999999 numbers, and one with 2 & 3

**Comment by liomj** [comment]
> BTW - if it easier for you, we could have two sets of test data, one with 999999 numbers, and one with 2 & 3

that would be better...thank you

**Comment by mambax7** [comment]
So what are we doing with these updates?  Will there be a conflict with your latest PR: https://github.com/XoopsModules25x/yogurt/pull/86

**Comment by liomj** [comment]
It should be able to merged and if any conflict can be resolve

By the way any update on the progress of the problems reported of this update

**Pull request merged**
